version: '2'
services:
    cambiosv1-app:
        image: cambiosv1
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cambiosv1-mysql:3306/cambiosv1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cambiosv1-mysql:
        extends:
            file: mysql.yml
            service: cambiosv1-mysql
